background_opacity 0.85

# mouse
copy_on_select yes
mouse_hide_wait 2.0

hide_window_decorations yes
#window_border_width 1pt
active_border_color #bd93f9
inactive_border_color #44475a
#window_margin_width 10

foreground           #f8f8f2
background           #1e1f29
selection_foreground #ffffff
selection_background #44475a
cursor               #f8f8f2

# tabs
active_tab_foreground   #282a36
active_tab_background   #bd93f9
inactive_tab_foreground #f8f8f2
inactive_tab_background #6272a4

# negro
color0 #21222c
color8 #6272a4

# rojo
color1 #ff5555
color9 #ff6e6e

# verde
color2  #50fa7b
color10 #69ff94

# amarillo
color3  #f1fa8c
color11 #ffffa5

# azul 
color4  #bd93f9
color12 #d6acff

# mg 
color5  #ff79c6
color13 #ff92d0

# cian 
color6  #8be9fd
color14 #a4ffff

# blanco 
color7  #f8f8f2
color15 #ffffff


# Font
font_family      "JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

